import { ProgressIndicator } from "std-widgets.slint";

component CenterBox inherits Rectangle {
    background: transparent;

    VerticalLayout {
        alignment: center;
        width: parent.width;
        height: parent.height;

        HorizontalLayout {
            alignment: center;
            width: parent.width;

            @children
        }
    }
}

export component App inherits Window {
    width: 500px;
    height: 430px;
    icon: @image-url("../images/icon.png");
    title: "AniLibria.Qt updater";

    property <string> downloadVersion: "0.0.0";
    property <int> downloadProgressValue: 50;
    
    Rectangle {
        background: transparent;
        width: parent.width;
        height: parent.height;
    
    VerticalLayout {
        spacing: 2px;

            CenterBox {
                width: parent.width;
                height: 40px;

        Text {
                    font-size: 18px;
                    text: "Install version " + downloadVersion;
                }    
            }
    
            CenterBox {
                width: parent.width;
                height: 20px;

                Text {
                    font-size: 16px;
                    text: "Download progress " + downloadProgressValue + "%";
                }
            }

            CenterBox {
                width: parent.width;
                height: 60px;
                
                ProgressIndicator {
                    width: parent.width - 40px;
                    height: 20px;
                    progress: (downloadProgressValue / 100);
        }
        /*Image {
            width: 100px;
            height: 100px;
            source: @image-url("../images/test.jpg");
        } */   
    }

            Rectangle {
            }
        }    
    }
}