# This starter workflow is for a CMake project running on multiple platforms. There is a different starter workflow if you just want a single platform.
# See: https://github.com/actions/starter-workflows/blob/main/ci/cmake-single-platform.yml
name: CMake on multiple platforms

on:
  push:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential dbus libmpv-dev pkg-config cmake
      - name: Install Qt
        uses: jurplel/install-qt-action@v4
        with:
          version: 6.8.3
          modules: qtscxml qt5compat qtimageformats qtwebsockets qtdbus
      - name: Configure
        run: cmake -S . -B build -DCMAKE_POLICY_VERSION_MINIMUM=3.5 -DCMAKE_BUILD_TYPE=Release
      - name: Build
        run: cmake --build build -t install
      - name: Build AppImage
        uses: AppImageCrafters/build-appimage@master
        env:
          UPDATE_INFO: gh-releases-zsync|anilibria|anilibria-winmaclinux|latest|*x86_64.AppImage.zsync
        with:
          recipe: appimage/AppImageBuilder.yml
      - uses: actions/upload-artifact@v4
        with:
          name: AppImage
          path: './*.AppImage*'
