name: Linux and macOS CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  ubuntuBuild:
    if: false
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: apt-update
      run: sudo apt-get update -qq
    - name: apt get dependencies
      run: sudo apt-get install cmake build-essential libmpv-dev pkg-config
    - name: Install Qt dependencies
      uses: jurplel/install-qt-action@v4
      with:
        version: 6.9
        target: 'desktop'
        modules: 'qtwebsockets'
    - name: test qml dir
      run: |
        ls
        tail -n 150 src/Views/Releases.qml
    - name: configure cmake
      run: cmake -S src -B build
    - name: build cmake
      run: cmake --build build -j$(nproc)
    - name: test dir
      run: |
        ls ../Qt/6.9.*/gcc_64/qml
    - name: prepare AppDir
      run: |
          [ -d "AppDir" ] && rm -rf "AppDir"
          patchelf --set-rpath '$ORIGIN/usr/lib' build/AniLiberty
          mkdir -p AppDir/usr/bin
          mkdir -p AppDir/usr/lib/plugins
          cp build/AniLiberty AppDir/usr/bin/
          cp appimage/AniLiberty.desktop AppDir/AniLiberty.desktop
          cp appimage/AniLiberty.png AppDir/AniLiberty.png
          chmod +x appimage/AppRun
          cp appimage/AppRun AppDir/AppRun          
          cp -r ../Qt/6.9.*/gcc_64/plugins/designer AppDir/usr/lib/plugins
          cp -r ../Qt/6.9.*/gcc_64/plugins/generic AppDir/usr/lib/plugins
          cp -r ../Qt/6.9.*/gcc_64/plugins/platforms AppDir/usr/lib/plugins
          cp -r ../Qt/6.9.*/gcc_64/plugins/imageformats AppDir/usr/lib/plugins
          cp -r ../Qt/6.9.*/gcc_64/plugins/iconengines AppDir/usr/lib/plugins
          cp -r ../Qt/6.9.*/gcc_64/plugins/platformthemes AppDir/usr/lib/plugins
          cp -r ../Qt/6.9.*/gcc_64/plugins/qmlls AppDir/usr/lib/plugins
          cp -r ../Qt/6.9.*/gcc_64/plugins/tls AppDir/usr/lib/plugins
          cp -r ../Qt/6.9.*/gcc_64/plugins/qmllint AppDir/usr/lib/plugins
          cp -r ../Qt/6.9.*/gcc_64/plugins/wayland-graphics-integration-client AppDir/usr/lib/plugins
          cp -r ../Qt/6.9.*/gcc_64/plugins/wayland-decoration-client AppDir/usr/lib/plugins
          cp -r ../Qt/6.9.*/gcc_64/plugins/wayland-shell-integration AppDir/usr/lib/plugins
          cp -r ../Qt/6.9.*/gcc_64/plugins/xcbglintegrations AppDir/usr/lib/plugins
          cp -r ../Qt/6.9.*/gcc_64/plugins/egldeviceintegrations AppDir/usr/lib/plugins
          cp -r ../Qt/6.9.*/gcc_64/plugins/platforminputcontexts AppDir/usr/lib/plugins
          cp -r ../Qt/6.9.*/gcc_64/plugins/networkinformation AppDir/usr/lib/plugins
          cp -r ../Qt/6.9.*/gcc_64/qml/QML AppDir/usr/lib/qml
          cp -r ../Qt/6.9.*/gcc_64/qml/Qt AppDir/usr/lib/qml
          cp -r ../Qt/6.9.*/gcc_64/qml/QtQml AppDir/usr/lib/qml
          cp -r ../Qt/6.9.*/gcc_64/qml/QtQuick AppDir/usr/lib/qml
          cp -r ../Qt/6.9.*/gcc_64/qml/QtWayland AppDir/usr/lib/qml
          python3 appimagedeps.py
    - name: Download and use appimagetool
      run: |
        wget -q -O appimagetool https://github.com/AppImage/appimagetool/releases/download/continuous/appimagetool-x86_64.AppImage
        chmod +x appimagetool
        ./appimagetool AppDir/
    - uses: actions/upload-artifact@v4
      with:
        name: deb-package
        path: AniLiberty-x86_64.AppImage
  macosbuild:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v4
    - uses: gerlero/brew-install@v1.1.2
      with:
        packages: pkgconf mpv
    - name: Install Qt dependencies
      uses: jurplel/install-qt-action@v4
      with:
        version: '6.8.3'
        target: 'desktop'
        arch: 'clang_64'
        modules: 'qtimageformats qtwebsockets'
    - name: configure
      run: cmake -S src -B .
    - name: run cmake
      run: cmake --build . --config Release --parallel 8
    - name: Run MacDeployQt
      run: macdeployqt AniLiberty.app -appstore-compliant -qmldir=.
    - name: show all libraries in app folder
      run: ls AniLiberty.app/Contents/Frameworks/
    - name: patch libraries paths
      run: |
        cp /opt/homebrew/opt/python@3.14/Frameworks/Python.framework/Versions/3.14/Python AniLiberty.app/Contents/Frameworks/
        
        install_name_tool -change /opt/homebrew/Cellar/ffmpeg/8.0.1/lib/libswresample.6.dylib @executable_path/../Frameworks/libswresample.6.dylib AniLiberty.app/Contents/Frameworks/libavcodec.62.dylib
        install_name_tool -change /opt/homebrew/Cellar/ffmpeg/8.0.1/lib/libavutil.60.dylib @executable_path/../Frameworks/libavutil.60.dylib AniLiberty.app/Contents/Frameworks/libavcodec.62.dylib
        install_name_tool -change /opt/homebrew/Cellar/ffmpeg/8.0.1/lib/libswscale.9.dylib @executable_path/../Frameworks/libswscale.9.dylib AniLiberty.app/Contents/Frameworks/libavfilter.11.dylib
        install_name_tool -change /opt/homebrew/Cellar/ffmpeg/8.0.1/lib/libavutil.60.dylib @executable_path/../Frameworks/libavutil.60.dylib AniLiberty.app/Contents/Frameworks/libavfilter.11.dylib
        install_name_tool -change /opt/homebrew/Cellar/ffmpeg/8.0.1/lib/libavcodec.62.dylib @executable_path/../Frameworks/libavcodec.62.dylib AniLiberty.app/Contents/Frameworks/libavfilter.11.dylib
        install_name_tool -change /opt/homebrew/Cellar/ffmpeg/8.0.1/lib/libavformat.62.dylib @executable_path/../Frameworks/libavformat.62.dylib AniLiberty.app/Contents/Frameworks/libavfilter.11.dylib
        install_name_tool -change /opt/homebrew/Cellar/ffmpeg/8.0.1/lib/libpostproc.58.dylib @executable_path/../Frameworks/libpostproc.58.dylib AniLiberty.app/Contents/Frameworks/libavfilter.11.dylib
        install_name_tool -change /opt/homebrew/Cellar/ffmpeg/8.0.1/lib/libswresample.6.dylib @executable_path/../Frameworks/libswresample.6.dylib AniLiberty.app/Contents/Frameworks/libavfilter.11.dylib
        
        install_name_tool -change /opt/homebrew/Cellar/ffmpeg/8.0.1/lib/libavutil.60.dylib @executable_path/../Frameworks/libavutil.60.dylib AniLiberty.app/Contents/Frameworks/libswresample.6.dylib
        install_name_tool -change /opt/homebrew/Cellar/ffmpeg/8.0.1/lib/libavutil.60.dylib @executable_path/../Frameworks/libavutil.60.dylib AniLiberty.app/Contents/Frameworks/libswscale.9.dylib

        install_name_tool -change /opt/homebrew/Cellar/ffmpeg/8.0.1/lib/libavcodec.62.dylib @executable_path/../Frameworks/libavcodec.62.dylib AniLiberty.app/Contents/Frameworks/libavformat.62.dylib
        install_name_tool -change /opt/homebrew/Cellar/ffmpeg/8.0.1/lib/libswresample.6.dylib @executable_path/../Frameworks/libswresample.6.dylib AniLiberty.app/Contents/Frameworks/libavformat.62.dylib
        install_name_tool -change /opt/homebrew/Cellar/ffmpeg/8.0.1/lib/libavutil.60.dylib @executable_path/../Frameworks/libavutil.60.dylib AniLiberty.app/Contents/Frameworks/libavformat.62.dylib

        install_name_tool -change /opt/homebrew/Cellar/ffmpeg/8.0.1/lib/libavfilter.11.dylib @executable_path/../Frameworks/libavfilter.11.dylib AniLiberty.app/Contents/Frameworks/libavdevice.62.dylib
        install_name_tool -change /opt/homebrew/Cellar/ffmpeg/8.0.1/lib/libswscale.9.dylib @executable_path/../Frameworks/libswscale.9.dylib AniLiberty.app/Contents/Frameworks/libavdevice.62.dylib
        install_name_tool -change /opt/homebrew/Cellar/ffmpeg/8.0.1/lib/libpostproc.58.dylib @executable_path/../Frameworks/libpostproc.58.dylib AniLiberty.app/Contents/Frameworks/libavdevice.62.dylib
        install_name_tool -change /opt/homebrew/Cellar/ffmpeg/8.0.1/lib/libavformat.62.dylib @executable_path/../Frameworks/libavformat.62.dylib AniLiberty.app/Contents/Frameworks/libavdevice.62.dylib
        install_name_tool -change /opt/homebrew/Cellar/ffmpeg/8.0.1/lib/libavcodec.62.dylib @executable_path/../Frameworks/libavcodec.62.dylib AniLiberty.app/Contents/Frameworks/libavdevice.62.dylib
        install_name_tool -change /opt/homebrew/Cellar/ffmpeg/8.0.1/lib/libswresample.6.dylib @executable_path/../Frameworks/libswresample.6.dylib AniLiberty.app/Contents/Frameworks/libavdevice.62.dylib
        install_name_tool -change /opt/homebrew/Cellar/ffmpeg/8.0.1/lib/libavutil.60.dylib @executable_path/../Frameworks/libavutil.60.dylib AniLiberty.app/Contents/Frameworks/libavdevice.62.dylib

        install_name_tool -change /opt/homebrew/Cellar/brotli/1.1.0/lib/libbrotlicommon.1.dylib @executable_path/../Frameworks/ AniLiberty.app/Contents/Frameworks/librubberband.3.dylib
        
        install_name_tool -change @loader_path/../../../../opt/libsamplerate/lib/libsamplerate.0.dylib @executable_path/../Frameworks/libhwy.1.dylib AniLiberty.app/Contents/Frameworks/librubberband.3.dylib
        
        install_name_tool -change /opt/homebrew/*/Python.framework/Versions/3.14/Python @executable_path/../Frameworks/Python AniLiberty.app/Contents/Frameworks/libvapoursynth-script.0.dylib
       
        hdiutil create -fs HFS+ -srcfolder AniLiberty.app/ -volname AniLiberty AniLiberty.dmg
    - name: TestRun
      run: |
        open -W AniLiberty.app --args testrun
        log show --predicate 'process == "AniLiberty"' --last 1h        
    - uses: actions/upload-artifact@v4
      with:
        name: macos
        path: AniLiberty.dmg
