name: UnfoldedRelease

on:
  push:
    branches: [ "master" ]
jobs:
  windows:
    runs-on: windows-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v6
    - name: Install .NET Core
      uses: actions/setup-dotnet@v5
      with:
        dotnet-version: 10.0.x
    - name: Restore dependencies
      run: dotnet restore unfolded/app/Aniliberty.Unfolded/Aniliberty.Unfolded.csproj
    - name: Publish x64 application
      run: dotnet publish -r win-x64 -c Release --self-contained true unfolded/app/Aniliberty.Unfolded/Aniliberty.Unfolded.csproj
    - name: Publish arm64 application
      run: dotnet publish -r win-arm64 -c Release --self-contained true unfolded/app/Aniliberty.Unfolded/Aniliberty.Unfolded.csproj
    - name: Copy binaries
      run: |
        cp unfolded/app/Aniliberty.Unfolded/bin/Release/net10.0/win-x64/publish/LocalCacheChecker.exe unfolded64.exe
        cp unfolded/app/Aniliberty.Unfolded/bin/Release/net10.0/win-arm64/publish/LocalCacheChecker.exe unfoldedarm64.exe
    - name: Upload x64 artifacts
      uses: actions/upload-artifact@v6
      with:
        name: unfolded64
        path: unfolded64.exe
    - name: Upload arm64 artifacts
      uses: actions/upload-artifact@v6
      with:
        name: unfoldedarm64
        path: unfoldedarm64.exe
